services:
  agent1_student:
    build: .
    container_name: agent1_student
    ports:
      - "8001:8000"
    networks:
      - ai_network
    environment:
      - COLLECTION=agent1_student

networks:
  ai_network:
    external: true
